// "use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

import { MeetingProviderComponent } from "./context/StoreContext";

const inter = Inter({ subsets: ["latin"] });

const metropolis_Font = localFont({
  src: [
    {
      path: '../public/fonts/Metropolis_Font_family/Metropolis-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Metropolis_Font_family/Metropolis-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Metropolis_Font_family/Metropolis-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-metropolis',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${metropolis_Font.variable} font-sans`}>
        <MeetingProviderComponent>
          {children}
        </MeetingProviderComponent>
      </body>
    </html>
  );
}
