version: 0.2  
    
phases:
  install:  
    commands:
      - apt-get update
      - apt-get install jq
      - export SONAR_TOKEN=01e95cb5f7de0db8851fa48f5ac10d30e45bd361
      - export PROJECTKEY=cecure-stream-webapp
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - ls
      - unzip ./sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - export PATH=$PATH:./sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin/
      - ls
      - echo $PATH
      - echo ##########################
      - ls ./sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin/
      # - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      # - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      # - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      # - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      # - export SONAR_SCANNER_OPTS="-server"
      
  build: 
    commands:
      - ls
      - pwd
    
      - sonar-scanner -Dsonar.organization=cecure-intelligence-limited -Dsonar.projectKey=$PROJECTKEY -Dsonar.sources=web-content -Dsonar.host.url=https://sonarcloud.io  > sonarqube_scanreport.json
      - sleep 10
      - sonar_task_id=$(cat sonarqube_scanreport.json | egrep -o "task\?id=[^ ]+" | cut -d'=' -f2)
      - sonar_analysis_id=$(curl -u $SONAR_TOKEN https://sonarcloud.io/api/ce/task\?id=$sonar_task_id | jq -r '.task.analysisId')
      #- project_status=$(curl -u $SONAR_TOKEN https://sonarcloud.io/api/qualitygates/project_status\?analysisId=$sonar_analysis_id | jq -r '.projectStatus.status')
      - curl -u $SONAR_TOKEN https://sonarcloud.io/api/qualitygates/project_status\?analysisId=$sonar_analysis_id > reports.json
      - cat reports.json
      #- curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECTKEY > analysis.json
      #- cat analysis.json
      #- project_status=$(curl -u $SONAR_TOKEN  https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECTKEY | jq -r '.projectStatus.status')
      #- echo $project_status
      #- echo ##########################
      #- project_status="SUCCESS"
      # - echo $project_status
      # - if [ $project_status = "ERROR" ]; then     exit 1; fi
        
  post_build:  
    commands:
      - echo Building Project
      - echo Finished Building