version: 0.2 
 
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
      
  build:
    commands:
      # Run Jest tests with coverage
      - cd web-content
      - ls
      - npm install jest
      - npm test
      - ls
      - cd coverage
      - pwd
      - ls
      - cat coverage-summary.json
      - COVERAGE_DATA=$(cat coverage-summary.json)

  post_build:
    commands:
      # Parse coverage data and check if it's greater than 50%
      - |
        LINES_TOTAL=$(echo "$COVERAGE_DATA" | jq -r '.total.lines.total')
        LINES_COVERED=$(echo "$COVERAGE_DATA" | jq -r '.total.lines.covered')
        LINES_PERCENTAGE=$(awk "BEGIN {print (${LINES_COVERED}/${LINES_TOTAL})*100}")

        FUNCTIONS_TOTAL=$(echo "$COVERAGE_DATA" | jq -r '.total.functions.total')
        FUNCTIONS_COVERED=$(echo "$COVERAGE_DATA" | jq -r '.total.functions.covered')
        FUNCTIONS_PERCENTAGE=$(awk "BEGIN {print (${FUNCTIONS_COVERED}/${FUNCTIONS_TOTAL})*100}")

        STATEMENTS_TOTAL=$(echo "$COVERAGE_DATA" | jq -r '.total.statements.total')
        STATEMENTS_COVERED=$(echo "$COVERAGE_DATA" | jq -r '.total.statements.covered')
        STATEMENTS_PERCENTAGE=$(awk "BEGIN {print (${STATEMENTS_COVERED}/${STATEMENTS_TOTAL})*100}")

        BRANCHES_TOTAL=$(echo "$COVERAGE_DATA" | jq -r '.total.branches.total')
        BRANCHES_COVERED=$(echo "$COVERAGE_DATA" | jq -r '.total.branches.covered')
        BRANCHES_PERCENTAGE=$(awk "BEGIN {print (${BRANCHES_COVERED}/${BRANCHES_TOTAL})*100}")

        OVERALL_COVERAGE=$(awk "BEGIN {print (${LINES_COVERED}+${FUNCTIONS_COVERED}+${STATEMENTS_COVERED}+${BRANCHES_COVERED})/(${LINES_TOTAL}+${FUNCTIONS_TOTAL}+${STATEMENTS_TOTAL}+${BRANCHES_TOTAL})*100}")

        echo "Overall Coverage: $OVERALL_COVERAGE%"
        
        if [ "$(awk -v n="$OVERALL_COVERAGE" 'BEGIN {print (n > 0 ? 1 : 0)}')" -eq 1 ]; then
          echo "Coverage is greater than 70%"
        else
          echo "Coverage is less than or equal to 70%"
          exit 1
        fi







