version: 0.2
phases:
  install:
    commands:
      - echo "install phase....."
  pre_build:
    commands:
      - chmod -R 775 $CODEBUILD_SRC_DIR/dependency-check/bin/dependency-check.sh
      - echo "stage pre_build completed"
  build:
    commands: 
      - cd dependency-check/bin
      - mkdir results
      - $CODEBUILD_SRC_DIR/dependency-check/bin/dependency-check.sh --project "wordpress" --format JUNIT --out results/results.xml --prettyPrint --enableExperimental --scan $CODEBUILD_SRC_DIR/web-content --exclude '$CODEBUILD_SRC_DIR/dependency-check/'
      - echo "OWASP dependency check analysis status is completed..."
      - cd results
      - cat results.xml
  post_build:
    commands:
reports:
  sca-reports:
    files:
      - dependency-check/bin/results/results.xml
    file-format: "JUNITXML"