version: 0.2
phases:
  install:
    commands:
      - echo "Starting the install phase..."
  pre_build:
    commands:
      - echo "Starting the pre_build phase..."
      - chmod +x $CODEBUILD_SRC_DIR/dependency-check/bin/dependency-check.sh
      - echo "Pre_build phase completed."
  build:
    commands:
      - echo "Starting the build phase..."
      - cd $CODEBUILD_SRC_DIR/dependency-check/bin
      - mkdir -p results
      - ./dependency-check.sh --project "wordpress" \
                              --format JUNIT \
                              --out results/results.xml \
                              --prettyPrint \
                              --enableExperimental \
                              --scan $CODEBUILD_SRC_DIR/web-content \
                              --exclude $CODEBUILD_SRC_DIR/dependency-check/
      - echo "OWASP Dependency Check analysis completed."
      - cd results
      - cat results.xml
  post_build:
    commands:
      - echo "Starting the post_build phase..."
      - echo "Post_build phase completed."
reports:
  sca-reports:
    files:
      - dependency-check/bin/results/results.xml
    file-format: JUNITXML