version: 0.2
phases:
  install:
    commands:
      - echo "install phase....."
  pre_build:
    commands:
      - chmod -R 775 $CODEBUILD_SRC_DIR/dependency-check/bin/dependency-check.sh
  build:
    commands:
      - mkdir -p results
      - ./dependency-check/bin/dependency-check.sh --project "wordpress" --format JUNIT --out results/results.xml --prettyPrint --enableExperimental --scan web-content --exclude dependency-check
  post_build:
    commands:
      - echo "Post build completed"
reports:
  sca-reports:
    files:
      - results/results.xml
    file-format: "JUNITXML"